name: db
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- anyio=4.0.0
- asttokens=2.4.1
- attrs=23.1.0
- aws-c-auth=0.7.5
- aws-c-cal=0.6.7
- aws-c-common=0.9.4
- aws-c-compression=0.2.17
- aws-c-event-stream=0.3.2
- aws-c-http=0.7.13
- aws-c-io=0.13.35
- aws-c-mqtt=0.9.8
- aws-c-s3=0.3.20
- aws-c-sdkutils=0.1.12
- aws-checksums=0.1.17
- aws-crt-cpp=0.24.4
- aws-sdk-cpp=1.11.182
- backports=1.0
- backports.functools_lru_cache=1.6.5
- black=23.10.1
- blosc=1.21.5
- branca=0.6.0
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- bzip2=1.0.8
- c-ares=1.21.0
- ca-certificates=2023.7.22
- cairo=1.18.0
- certifi=2023.7.22
- cffi=1.16.0
- cfitsio=4.3.0
- charset-normalizer=3.3.2
- click=8.1.7
- click-plugins=1.1.1
- cligj=0.7.2
- colorama=0.4.6
- comm=0.1.4
- contourpy=1.2.0
- cryptography=41.0.5
- cycler=0.12.1
- debugpy=1.8.0
- decorator=5.1.1
- dnspython=2.4.2
- exceptiongroup=1.1.3
- executing=2.0.1
- expat=2.5.0
- fastcore=1.5.29
- fastprogress=1.0.3
- filprofiler=2023.3.1
- fiona=1.9.5
- folium=0.14.0
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.44.0
- freetype=2.12.1
- freexl=2.0.0
- gdal=3.7.3
- geographiclib=1.52
- geopandas=0.14.0
- geopandas-base=0.14.0
- geopy=2.4.0
- geos=3.12.0
- geotiff=1.7.1
- gettext=0.21.1
- gflags=2.2.2
- giflib=5.2.1
- glog=0.6.0
- h11=0.14.0
- h2=4.1.0
- hdf4=4.2.15
- hdf5=1.14.2
- hpack=4.0.0
- httpcore=1.0.1
- hyperframe=6.0.1
- icu=73.2
- idna=3.4
- importlib-metadata=6.8.0
- importlib_metadata=6.8.0
- ipykernel=6.26.0
- ipython=8.17.2
- ipywidgets=8.1.1
- jedi=0.19.1
- jinja2=3.1.2
- joblib=1.3.2
- json-c=0.17
- jupyter_client=8.5.0
- jupyter_core=5.5.0
- jupyterlab_widgets=3.0.9
- kealib=1.5.2
- keyutils=1.6.1
- kiwisolver=1.4.5
- krb5=1.21.2
- lcms2=2.15
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libabseil=20230802.1
- libaec=1.1.2
- libarchive=3.7.2
- libarrow=13.0.0
- libblas=3.9.0
- libboost-headers=1.82.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libcrc32c=1.1.2
- libcurl=8.4.0
- libdeflate=1.19
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.12
- libexpat=2.5.0
- libffi=3.4.2
- libgcc-ng=13.2.0
- libgdal=3.7.3
- libgfortran-ng=13.2.0
- libgfortran5=13.2.0
- libglib=2.78.0
- libgomp=13.2.0
- libgoogle-cloud=2.12.0
- libgrpc=1.59.2
- libiconv=1.17
- libjpeg-turbo=3.0.0
- libkml=1.3.0
- liblapack=3.9.0
- libnetcdf=4.9.2
- libnghttp2=1.55.1
- libnsl=2.0.1
- libnuma=2.0.16
- libopenblas=0.3.24
- libpng=1.6.39
- libpq=16.0
- libprotobuf=4.24.4
- libre2-11=2023.06.02
- librttopo=1.1.0
- libsodium=1.0.18
- libspatialindex=1.9.3
- libspatialite=5.1.0
- libsqlite=3.44.0
- libssh2=1.11.0
- libstdcxx-ng=13.2.0
- libthrift=0.19.0
- libtiff=4.6.0
- libutf8proc=2.8.0
- libuuid=2.38.1
- libwebp-base=1.3.2
- libxcb=1.15
- libxml2=2.11.5
- libzip=1.10.1
- libzlib=1.2.13
- line_profiler=4.1.1
- lz4-c=1.9.4
- lzo=2.10
- mapclassify=2.6.1
- markdown-it-py=3.0.0
- markupsafe=2.1.3
- matplotlib-base=3.8.1
- matplotlib-inline=0.1.6
- mdurl=0.1.0
- minizip=4.0.2
- munch=4.0.0
- munkres=1.1.4
- mypy_extensions=1.0.0
- ncurses=6.4
- nest-asyncio=1.5.8
- networkx=3.2.1
- nspr=4.35
- nss=3.94
- numpy=1.26.0
- openjpeg=2.5.0
- openssl=3.1.4
- orc=1.9.0
- packaging=23.2
- pandas=2.1.2
- parso=0.8.3
- pathspec=0.11.2
- pcre2=10.40
- pexpect=4.8.0
- pickleshare=0.7.5
- pillow=10.1.0
- pip=23.3.1
- pixman=0.42.2
- platformdirs=3.11.0
- poppler=23.10.0
- poppler-data=0.4.12
- postgresql=16.0
- proj=9.3.0
- prompt-toolkit=3.0.39
- prompt_toolkit=3.0.39
- psutil=5.9.5
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pure_eval=0.2.2
- pyarrow=13.0.0
- pycparser=2.21
- pygments=2.16.1
- pymongo=4.6.0
- pyodbc=5.0.1
- pyparsing=3.1.1
- pyproj=3.6.1
- pysocks=1.7.1
- python=3.11.6
- python-dateutil=2.8.2
- python-dotenv=1.0.0
- python-tzdata=2023.3
- python_abi=3.11
- pytz=2023.3.post1
- pyzmq=25.1.1
- rdma-core=28.9
- re2=2023.06.02
- readline=8.2
- requests=2.31.0
- rich=13.6.0
- rtree=1.1.0
- ruff=0.1.4
- s2n=1.3.55
- scikit-learn=1.3.2
- scipy=1.11.3
- setuptools=68.2.2
- shapely=2.0.2
- shellingham=1.5.4
- six=1.16.0
- snappy=1.1.10
- sniffio=1.3.0
- sqlite=3.44.0
- stack_data=0.6.2
- threadpoolctl=3.2.0
- tiledb=2.16.3
- tk=8.6.13
- tornado=6.3.3
- tqdm=4.66.1
- traitlets=5.13.0
- typer=0.9.0
- typing-extensions=4.8.0
- typing_extensions=4.8.0
- tzcode=2023c
- tzdata=2023c
- ucx=1.15.0
- unixodbc=2.3.12
- uriparser=0.9.7
- urllib3=2.0.7
- wcwidth=0.2.9
- wheel=0.41.3
- widgetsnbextension=4.0.9
- xerces-c=3.2.4
- xmltodict=0.13.0
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.7
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.11
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xyzservices=2023.10.1
- xz=5.2.6
- zeromq=4.3.5
- zipp=3.17.0
- zlib=1.2.13
- zstd=1.5.5

