name: db_new
channels:
- conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=4.5
- aiohttp=3.9.3
- aiohttp-cors=0.7.0
- aiosignal=1.3.1
- annotated-types=0.6.0
- anyio=4.3.0
- asttokens=2.4.1
- astunparse=1.6.3
- async-timeout=4.0.3
- attrs=23.2.0
- aws-c-auth=0.7.11
- aws-c-cal=0.6.9
- aws-c-common=0.9.12
- aws-c-compression=0.2.17
- aws-c-event-stream=0.4.1
- aws-c-http=0.8.0
- aws-c-io=0.14.0
- aws-c-mqtt=0.10.1
- aws-c-s3=0.4.9
- aws-c-sdkutils=0.1.13
- aws-checksums=0.1.17
- aws-crt-cpp=0.26.0
- aws-sdk-cpp=1.11.210
- azure-core-cpp=1.10.3
- azure-storage-blobs-cpp=12.10.0
- azure-storage-common-cpp=12.5.0
- blessed=1.19.1
- blosc=1.21.5
- bokeh=3.3.4
- branca=0.7.1
- brotli=1.1.0
- brotli-bin=1.1.0
- brotli-python=1.1.0
- bzip2=1.0.8
- c-ares=1.27.0
- ca-certificates=2024.2.2
- cachetools=5.3.3
- cairo=1.18.0
- certifi=2024.2.2
- cffi=1.16.0
- cfitsio=4.3.1
- charset-normalizer=3.3.2
- click=8.1.7
- click-plugins=1.1.1
- cligj=0.7.2
- cloudpickle=3.0.0
- colorama=0.4.6
- colorful=0.5.4
- comm=0.2.1
- contourpy=1.2.0
- cryptography=41.0.7
- cycler=0.12.1
- cytoolz=0.12.3
- dask=2024.2.1
- dask-core=2024.2.1
- debugpy=1.8.1
- decorator=5.1.1
- distlib=0.3.8
- distributed=2024.2.1
- dnspython=2.6.1
- exceptiongroup=1.2.0
- execnb=0.1.5
- executing=2.0.1
- expat=2.5.0
- fastcore=1.5.29
- fastprogress=1.0.3
- filelock=3.13.1
- filprofiler=2023.3.1
- fiona=1.9.5
- folium=0.15.1
- font-ttf-dejavu-sans-mono=2.37
- font-ttf-inconsolata=3.000
- font-ttf-source-code-pro=2.038
- font-ttf-ubuntu=0.83
- fontconfig=2.14.2
- fonts-conda-ecosystem=1
- fonts-conda-forge=1
- fonttools=4.49.0
- freetype=2.12.1
- freexl=2.0.0
- frozenlist=1.4.1
- fsspec=2024.2.0
- gdal=3.8.4
- geographiclib=2.0
- geopandas=0.14.3
- geopandas-base=0.14.3
- geopy=2.4.1
- geos=3.12.1
- geotiff=1.7.1
- gettext=0.21.1
- gflags=2.2.2
- ghapi=1.0.4
- giflib=5.2.1
- glog=0.6.0
- google-api-core=2.17.1
- google-auth=2.28.1
- googleapis-common-protos=1.62.0
- gpustat=1.1.1
- grpcio=1.59.3
- h11=0.14.0
- h2=4.1.0
- hdf4=4.2.15
- hdf5=1.14.3
- hpack=4.0.0
- httpcore=1.0.4
- hyperframe=6.0.1
- icu=73.2
- idna=3.6
- importlib-metadata=7.0.1
- importlib_metadata=7.0.1
- importlib_resources=6.1.2
- ipykernel=6.29.3
- ipython=8.22.1
- ipywidgets=8.1.2
- jedi=0.19.1
- jinja2=3.1.3
- joblib=1.3.2
- json-c=0.17
- jsonschema=4.21.1
- jsonschema-specifications=2023.12.1
- jupyter_client=8.6.0
- jupyter_core=5.7.1
- jupyterlab_widgets=3.0.10
- kealib=1.5.3
- keyutils=1.6.1
- kiwisolver=1.4.5
- krb5=1.21.2
- lcms2=2.16
- ld_impl_linux-64=2.40
- lerc=4.0.0
- libabseil=20230802.1
- libaec=1.1.2
- libarchive=3.7.2
- libarrow=15.0.0
- libarrow-acero=15.0.0
- libarrow-dataset=15.0.0
- libarrow-flight=15.0.0
- libarrow-flight-sql=15.0.0
- libarrow-gandiva=15.0.0
- libarrow-substrait=15.0.0
- libblas=3.9.0
- libboost-headers=1.84.0
- libbrotlicommon=1.1.0
- libbrotlidec=1.1.0
- libbrotlienc=1.1.0
- libcblas=3.9.0
- libcrc32c=1.1.2
- libcurl=8.5.0
- libdeflate=1.19
- libedit=3.1.20191231
- libev=4.33
- libevent=2.1.12
- libexpat=2.5.0
- libffi=3.4.2
- libgcc-ng=13.2.0
- libgdal=3.8.4
- libgfortran-ng=13.2.0
- libgfortran5=13.2.0
- libglib=2.78.4
- libgomp=13.2.0
- libgoogle-cloud=2.12.0
- libgrpc=1.59.3
- libiconv=1.17
- libjpeg-turbo=3.0.0
- libkml=1.3.0
- liblapack=3.9.0
- libllvm15=15.0.7
- libnetcdf=4.9.2
- libnghttp2=1.58.0
- libnl=3.9.0
- libnsl=2.0.1
- libnuma=2.0.16
- libopenblas=0.3.26
- libparquet=15.0.0
- libpng=1.6.43
- libpq=16.2
- libprotobuf=4.24.4
- libre2-11=2023.09.01
- librttopo=1.1.0
- libsodium=1.0.18
- libspatialindex=1.9.3
- libspatialite=5.1.0
- libsqlite=3.45.1
- libssh2=1.11.0
- libstdcxx-ng=13.2.0
- libthrift=0.19.0
- libtiff=4.6.0
- libunwind=1.6.2
- libutf8proc=2.8.0
- libuuid=2.38.1
- libuv=1.46.0
- libwebp-base=1.3.2
- libxcb=1.15
- libxcrypt=4.4.36
- libxml2=2.12.5
- libzip=1.10.1
- libzlib=1.2.13
- locket=1.0.0
- lz4=4.3.3
- lz4-c=1.9.4
- lzo=2.10
- mapclassify=2.6.1
- markdown-it-py=3.0.0
- markupsafe=2.1.5
- matplotlib-base=3.8.3
- matplotlib-inline=0.1.6
- mdurl=0.1.2
- minizip=4.0.4
- modin=0.27.0
- modin-core=0.27.0
- modin-dask=0.27.0
- modin-ray=0.27.0
- msgpack-python=1.0.7
- multidict=6.0.5
- munkres=1.1.4
- nbdev=2.2.10
- ncurses=6.4
- nest-asyncio=1.6.0
- networkx=3.2.1
- nodejs=20.9.0
- nspr=4.35
- nss=3.98
- numpy=1.26.4
- nvidia-ml-py=12.535.133
- opencensus=0.11.3
- opencensus-context=0.1.3
- openjpeg=2.5.2
- openssl=3.2.1
- orc=1.9.2
- packaging=23.2
- pandas=2.2.1
- parso=0.8.3
- partd=1.4.1
- pcre2=10.42
- pexpect=4.9.0
- pickleshare=0.7.5
- pillow=10.2.0
- pip=24.0
- pixman=0.43.2
- pkgutil-resolve-name=1.3.10
- platformdirs=3.11.0
- poppler=24.02.0
- poppler-data=0.4.12
- postgresql=16.2
- proj=9.3.1
- prometheus_client=0.20.0
- prompt-toolkit=3.0.42
- protobuf=4.24.4
- psutil=5.9.8
- pthread-stubs=0.4
- ptyprocess=0.7.0
- pure_eval=0.2.2
- py-spy=0.3.14
- pyarrow=15.0.0
- pyarrow-hotfix=0.6
- pyasn1=0.5.1
- pyasn1-modules=0.3.0
- pycparser=2.21
- pydantic=2.6.3
- pydantic-core=2.16.3
- pygments=2.17.2
- pymongo=4.6.2
- pyodbc=5.1.0
- pyopenssl=24.0.0
- pyparsing=3.1.1
- pyproj=3.6.1
- pysocks=1.7.1
- python=3.11.8
- python-dateutil=2.8.2
- python-dotenv=1.0.1
- python-tzdata=2024.1
- python_abi=3.11
- pytz=2024.1
- pyu2f=0.1.5
- pyyaml=6.0.1
- pyzmq=25.1.2
- ray-core=2.9.2
- ray-default=2.9.2
- rdma-core=50.0
- re2=2023.09.01
- readline=8.2
- referencing=0.33.0
- requests=2.31.0
- rich=13.7.1
- rpds-py=0.18.0
- rsa=4.9
- rtree=1.2.0
- ruff=0.2.2
- s2n=1.4.1
- scikit-learn=1.4.1.post1
- scipy=1.12.0
- setproctitle=1.3.3
- setuptools=69.1.1
- shapely=2.0.3
- shellingham=1.5.4
- six=1.16.0
- smart_open=7.0.1
- snappy=1.1.10
- sniffio=1.3.1
- sortedcontainers=2.4.0
- sqlite=3.45.1
- stack_data=0.6.2
- tblib=3.0.0
- threadpoolctl=3.3.0
- tiledb=2.20.0
- tk=8.6.13
- toolz=0.12.1
- tornado=6.4
- tqdm=4.66.2
- traitlets=5.14.1
- typer=0.9.0
- typing-extensions=4.10.0
- typing_extensions=4.10.0
- tzcode=2024a
- tzdata=2024a
- ucx=1.15.0
- unixodbc=2.3.12
- uriparser=0.9.7
- urllib3=2.2.1
- virtualenv=20.21.0
- wcwidth=0.2.13
- wheel=0.42.0
- widgetsnbextension=4.0.10
- wrapt=1.16.0
- xerces-c=3.2.5
- xmltodict=0.13.0
- xorg-kbproto=1.0.7
- xorg-libice=1.1.1
- xorg-libsm=1.2.4
- xorg-libx11=1.8.7
- xorg-libxau=1.0.11
- xorg-libxdmcp=1.1.3
- xorg-libxext=1.3.4
- xorg-libxrender=0.9.11
- xorg-renderproto=0.11.1
- xorg-xextproto=7.3.0
- xorg-xproto=7.0.31
- xyzservices=2023.10.1
- xz=5.2.6
- yaml=0.2.5
- yarl=1.9.4
- zeromq=4.3.5
- zict=3.0.0
- zipp=3.17.0
- zlib=1.2.13
- zstd=1.5.5

