# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03a_anatel.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/03a_anatel.ipynb 3
import os
from typing import List, Union

import numpy as np
import pandas as pd
from dotenv import find_dotenv, load_dotenv

from .datasources.sitarweb import Stel, Radcom, SQLSERVER_PARAMS
from .datasources.mosaico import MONGO_URI
from .datasources.srd import SRD
from .datasources.telecom import Telecom
from .datasources.smp import SMP

# %% ../nbs/03a_anatel.ipynb 4
load_dotenv(find_dotenv())
