# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/10_smp.ipynb.

# %% auto 0
__all__ = ['SMP']

# %% ../nbs/10_smp.ipynb 2
from fastcore.xtras import Path
import pandas as pd
from dataclasses import dataclass
from fastcore.xtras import Path
from fastcore.foundation import GetAttr
import pandas as pd
from .connectors import DBConnectors

# %% ../nbs/10_smp.ipynb 3
@dataclass
class SMP:
    connector: DBConnectors = DBConnectors()
