# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/03b_aero.ipynb.

# %% auto 0
__all__ = ['Aero']

# %% ../../nbs/03b_aero.ipynb 3
import os
from typing import List, Union

import numpy as np
import pandas as pd
from dotenv import find_dotenv, load_dotenv
from .icao import get_icao
from .aisweb import get_aisw
from .aisgeo import get_aisg
from .redemet import get_redemet
from .base import Base

# %% ../../nbs/03b_aero.ipynb 4
load_dotenv(find_dotenv())

# %% ../../nbs/03b_aero.ipynb 5
class Aero(Base):
    pass

# %% ../../nbs/03b_aero.ipynb 9
if __name__ == "__main__":
    print(f'{50*"="}ICAO{50*"="}')
    icao = get_icao()
    display(icao)
    print(f'{50*"="}AISWEB{50*"="}')
    aisw = get_aisw()
    display(aisw)
    print(f'{50*"="}AISGEO{50*"="}')
    aisg = get_aisg()
    print(f'{50*"="}REDEMET{50*"="}')
    redemet = get_redemet()
