ipynb-filters: [nbdev_filter]

project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  title: "Estações Licenciadas de Telecomunicações e Radiodifusão"
  description: "This repository hold automation scripts to fetch, clean and merge data from licensed telecomunications entities available at ANATEL Database Systems."
  execute: 
    enabled: false
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: https://github.com/ronaldokun/anateldb
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/ronaldokun/anateldb
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
